#!/bin/bash

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd -P)
REPO_ROOT="${SCRIPT_DIR}/.."

FILE=$1
shift
EXTRA_FLAGS=$@
OUTPUT_DIR=${OUTPUT_DIR:-"$REPO_ROOT/build"}
OUTPUT_PATH=${OUTPUT_PATH:-""}
CLANG_INCLUDES=${CLANG_INCLUDES:-"$REPO_ROOT/lib $REPO_ROOT/lib/fishhook $REPO_ROOT/lib/utils"}
CLANG_SOURCES=${CLANG_SOURCES:-"$REPO_ROOT/lib/fishhook/fishhook.c"}
CLANG_FRAMEWORKS=${CLANG_FRAMEWORKS:-"CoreAudio AVFoundation CoreMedia CoreVideo AudioToolbox UIKit Foundation"}
CLANG_INCLUDES="$CLANG_INCLUDES $CLANG_EXTRA_INCLUDES"
CLANG_SOURCES="$CLANG_SOURCES $CLANG_EXTRA_SOURCES"
CLANG_FRAMEWORKS="$CLANG_FRAMEWORKS $CLANG_EXTRA_FRAMEWORKS"

FILE="${FILE%.*}"
NAME=$(basename "$FILE")

set -e
SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)

if [ -z "$FILE" ]; then
	echo "Usage: $0 <FILE>"
	exit 1
fi

if [ ! -f "$FILE.m" ]; then
	echo "Error: $FILE.m not found"
	exit 1
fi

if [ -z "$OUTPUT_PATH" ]; then
	OUTPUT_PATH="$OUTPUT_DIR/$NAME.dylib"
fi

FLAGS="-dynamiclib -arch arm64 -isysroot $SDK_PATH"
for INCLUDE in $CLANG_INCLUDES; do
	FLAGS="$FLAGS -I $INCLUDE"
done

for FRAMEWORK in $CLANG_FRAMEWORKS; do
	FLAGS="$FLAGS -framework $FRAMEWORK"
done

FLAGS="$FLAGS $EXTRA_FLAGS"
FLAGS="$FLAGS -o $OUTPUT_PATH"
FLAGS="$FLAGS $FILE.m $CLANG_SOURCES"

mkdir -p $OUTPUT_DIR

echo clang $FLAGS
clang $FLAGS
