#!/bin/bash

# Usage: ./scripts/serve tweaks/whatsapp/MicSpoof
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd -P)
REPO_ROOT="${SCRIPT_DIR}/.."
FILENAME=$1
NAME=$(basename "$FILENAME")
IP_MAC="192.168.1.23"
P12_FILE="$REPO_ROOT/.secrets/SideStoreSigningCertificate.p12"
P12_PASS="abc"

if [ ! -f "$REPO_ROOT/$FILENAME.m" ]; then
    echo "Error: $REPO_ROOT/$FILENAME.m does not exist"
    exit 1
fi

set -e

# 1. Build the Binary
echo "[*] Compiling $FILENAME.m..."
"$REPO_ROOT/scripts/compile.sh" $FILENAME

# 2. Keychain Setup
KC_NAME="$REPO_ROOT/build/build.keychain"
KC_PASS="temp"
ORIG_KC_LIST=$(security list-keychains -d user | xargs)

# Cleanup function to restore keychain list on exit
cleanup() {
    echo "[*] Cleaning up keychain..."
    security list-keychains -d user -s $ORIG_KC_LIST
    security delete-keychain "$KC_NAME" || true
}
trap cleanup EXIT

echo "[*] Preparing Signing Identity..."
security create-keychain -p "$KC_PASS" "$KC_NAME"
security unlock-keychain -p "$KC_PASS" "$KC_NAME"

# Add temp keychain to search list
security list-keychains -d user -s "$KC_NAME" $ORIG_KC_LIST

# 3. Handle Certificate (Legacy Fix)
openssl pkcs12 -in "$P12_FILE" -out "$REPO_ROOT/build/temp.pem" -nodes -passin pass:"$P12_PASS"
openssl pkcs12 -export -in "$REPO_ROOT/build/temp.pem" -out "$REPO_ROOT/build/legacy.p12" -passout pass:"$P12_PASS" -legacy
rm "$REPO_ROOT/build/temp.pem"

security import "$REPO_ROOT/build/legacy.p12" -k "$KC_NAME" -P "$P12_PASS" -T /usr/bin/codesign
rm "$REPO_ROOT/build/legacy.p12"

# 4. Sign the dylib
echo "[*] Signing dylib..."
IDENTITY=$(security find-identity -v -p codesigning "$KC_NAME" | head -n 1 | awk -F '"' '{print $2}')

if [ -z "$IDENTITY" ]; then
    echo "Error: Identity not found in keychain."
    exit 1
fi

echo "IDENTITY: $IDENTITY"

codesign --sign "$IDENTITY" --timestamp=none "$REPO_ROOT/build/$NAME.dylib"

# 5. Verify
echo "[*] Signature Verification:"
codesign -dvvv "$REPO_ROOT/build/$NAME.dylib" 2>&1 | grep "Authority"

# 6. Start Deployment
echo "[*] Starting Log Listener (TCP 8889) in background..."
#nc -l 8889 &

echo "[!] Ready! Launch the app on iPhone now."
echo "[*] Sending dylib to iPhone on TCP 8887..."
#cat build/$FILENAME.dylib | nc -l 8887
python3 "$REPO_ROOT/scripts/bridgenew.py"# build/$NAME.dylib

echo "[*] Done. Streaming logs below:"
wait
